version: "3"
services: 
    db:
      image: mariadb:latest
      environment: 
      - MYSQL_ROOT_PASSWORD=dalongrong
      volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      ports: 
      - "3306:3306"